<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251210205544 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contenu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, corps VARCHAR(255) NOT NULL, publier BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercice_respiration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, duree_inspiration INT NOT NULL, duree_apnee INT NOT NULL, duree_expiration INT NOT NULL, publier BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE session_exercice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, utilisateur_id INT DEFAULT NULL, exercice_respiration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FB4A725FB88E14F ON session_exercice (utilisateur_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6FB4A725D2D7F70 ON session_exercice (exercice_respiration_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE session_exercice ADD CONSTRAINT FK_6FB4A725FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE session_exercice ADD CONSTRAINT FK_6FB4A725D2D7F70 FOREIGN KEY (exercice_respiration_id) REFERENCES exercice_respiration (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE session_exercice DROP CONSTRAINT FK_6FB4A725FB88E14F');
        $this->addSql('ALTER TABLE session_exercice DROP CONSTRAINT FK_6FB4A725D2D7F70');
        $this->addSql('DROP TABLE contenu');
        $this->addSql('DROP TABLE exercice_respiration');
        $this->addSql('DROP TABLE session_exercice');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
